### ISSUE TITLE
Codes for Fig3(H & I)

### ISSUE THREAD

**Issue by AteeqMKhaliq** [IzarLab/Melanoma_Brain_Metastasis#2]
Hi,
Congrats on publishing such a wounderful research paper on Brain Mets, It's beautiful and fascinating. Thank you for sharing such a treasure trove. 
I am looking to recreate Figure 3 (H-I)((H) Spearman correlation of individual programs from cancer cells and metaprograms (MP) (black boxes) using KINOMO; left bar indicating tissue origin. (I) Normalized gene contribution of MPs (columns) identified in (H) and biological function (left)). Can you please share the codes for the same? It would be beneficial if you could share the codes. 
Thanks again,
Regards,
AMK

**Comment by somnathtagore** [comment]
Hi,

Can you please follow the readme file with the KINOMO repo? You should see a downstream_analysis folder with the relevant scripts.

Thanks!

**Comment by AteeqMKhaliq** [comment]
Hi Somnath,
Thanks a lot for the quick reply, I am not able to find the Correlation heatmap generated in H and the Biological functions (Fig I), if you can help me in getting that I would be of great help.
Thanks a lot,
AMK

**Comment by somnathtagore** [comment]
Hi,

What is your input data for generating the heatmap? 
Did you perform the factorization on all samples separately? And finally, do you have the factors for all the samples?

Thanks!

**Comment by AteeqMKhaliq** [comment]
I have used raw counts and did factorisation as well for individual samples. but I am not able to pass through Fig H, as shown in the manuscript. Also, let me know how Fig I is generated, and what package was used for this.
Thanks.

**Comment by somnathtagore** [comment]
Hi,
If you are using R, then you can use the cor() function and select "Spearman" or "Pearson" based on your dataset. For getting optimal number of clusters, you can use Ward’s method.
For Figure 3I, please follow the readme file (for Normalized gene expression).
Thanks.
