### ISSUE TITLE
Codes for spatial transcriptomics

### ISSUE THREAD

**Issue by R2L23** [IzarLab/Melanoma_Brain_Metastasis#3]
Hello, thank you for sharing your code, which has been very helpful to me. I'm pretty new to spatial transcriptomics analysis, and I noticed that the "Spatial_analysis" folder doesn't seem to include the "brain_mets_analyze_puck.R" and "brain_mets_spatial_analysis.R" scripts. Would it be possible for you to share those with me?
Can I analyze the Slide-seq v2 data by following the Seurat v5 tutorial?
thanks a lot!

**Comment by yipingwang12** [comment]
Hello, thank you for your interest in our code. I am sorry that we forgot to upload the two scripts you mentioned, but they are now available in the Spatial_analysis folder.

The brain_mets_analyze_puck.R script is based on the Seurat v5 tutorial, but we added some analyses that are not in the tutorial, so we recommend you use our script instead.
